networks:
  inlap-network:
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: inlap-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=${SA_PASSWORD:-Password1!}
    ports:
      - "1433:1433"
    networks:
      - inlap-network
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: InLap.Api/Dockerfile
    container_name: inlap-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver;Database=InLap;User=sa;Password=${SA_PASSWORD:-Password1!};TrustServerCertificate=True;
      - FILES_BASE_PATH=/data/files
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - inlap-network
    restart: unless-stopped